CREATE TABLE IF NOT EXISTS `anag_user` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `SURNAME` varchar(100) DEFAULT NULL,
  `COD_FISC` varchar(16) DEFAULT NULL,
  `P_IVA` varchar(11) DEFAULT NULL,
  `REFERENCE` int(11) DEFAULT NULL,
  `READ_PERMISSION` varchar(1) NOT NULL DEFAULT 'S',
  `WRITE_PERMISSION` varchar(1) NOT NULL DEFAULT 'N',
  `EMAIL` varchar(100) DEFAULT NULL,
  `PHONE` varchar(20) DEFAULT NULL,
  `PSW` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REFERENCE_ID_idx` (`REFERENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `anag_user` (`ID`, `NAME`, `SURNAME`, `COD_FISC`, `P_IVA`, `REFERENCE`, `READ_PERMISSION`, `WRITE_PERMISSION`, `EMAIL`, `PHONE`, `PSW`) VALUES
(0, 'ADMIN', 'ADMIN', 'ADMIN', 'AAAAA', NULL, 'S', 'S', 'ADMIN@ADMIN.it', '3332211456', 'ADMIN'),
(1, 'ADMIN2', 'ADMIN2', 'ADMIN2', NULL, 0, 'S', 'S', 'ADMIN2@ADMIN2.IT', NULL, 'ADMIN2'),
(2, 'ADMIN3', 'ADMIN3', 'ADMIN3', NULL, 1, 'S', 'N', 'ADMIN3@ADMIN3.IT', NULL, 'ADMIN3'),
(3, 'ADMIN', 'ADMIN', 'ADMIN', 'AAAAA', 1, 'S', 'S', 'ADMIN@ADMIN.it', '3332211456', 'ADMIN'),
(4, 'ADMIN2', 'ADMIN2', 'ADMIN2', NULL, 1, 'S', 'S', 'ADMIN2@ADMIN2.IT', NULL, 'ADMIN2'),
(5, 'ADMIN3', 'ADMIN3', 'ADMIN3', NULL, 7, 'S', 'N', 'ADMIN3@ADMIN3.IT', NULL, 'ADMIN3'),
(6, 'ADMIN', 'ADMIN', 'ADMIN', 'AAAAA', 1, 'S', 'S', 'ADMIN@ADMIN.it', '3332211456', 'ADMIN'),
(7, 'ADMIN2', 'ADMIN2', 'ADMIN2', NULL, 0, 'S', 'S', 'ADMIN2@ADMIN2.IT', NULL, 'ADMIN2'),
(8, 'ADMIN3', 'ADMIN3', 'ADMIN3', NULL, 7, 'S', 'N', 'ADMIN3@ADMIN3.IT', NULL, 'ADMIN3');

CREATE TABLE IF NOT EXISTS `app_activation` (
  `ID` int(11) NOT NULL,
  `USER` int(11) NOT NULL,
  `DES_ACTIVATION` varchar(100) NOT NULL,
  `AMNT_PLAFONT` int(11) NOT NULL,
  `DAT_ATT` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ACT_USER_idx` (`USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `app_activation` (`ID`, `USER`, `DES_ACTIVATION`, `AMNT_PLAFONT`, `DAT_ATT`) VALUES
(0, 2, 'ATTIVAZIONE PROVA', 20, '05-11-2017'),
(1, 8, 'ATTIVAZIONE PROVA', 20, '05-11-2017'),
(2, 5, 'ATTIVAZIONE PROVA', 20, '05-11-2017'),
(3, 4, 'ATTIVAZIONE PROVA', 20, '05-11-2017');

CREATE TABLE IF NOT EXISTS `app_hierarchy` (
`bottom` int(11)
,`center` int(11)
,`top` int(11)
);

CREATE TABLE IF NOT EXISTS `app_transactions` (
  `ID` int(11) NOT NULL,
  `USER` int(11) NOT NULL,
  `DAT_MOV` varchar(10) NOT NULL,
  `AMOUNT` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_AMOUNT_idx` (`USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `app_transactions` (`ID`, `USER`, `DAT_MOV`, `AMOUNT`) VALUES
(0, 0, '05-11-2017', 20),
(1, 0, '05-11-2017', 20),
(2, 0, '05-11-2017', 20),
(3, 0, '05-11-2017', 20),
(4, 0, '05-11-2017', 20),
(5, 0, '05-11-2017', -20),
(6, 0, '05-11-2017', -20);

DROP TABLE IF EXISTS `app_hierarchy`;

CREATE ALGORITHM=UNDEFINED DEFINER=`Sql1151252`@`%` SQL SECURITY DEFINER VIEW `app_hierarchy` AS select `a`.`ID` AS `bottom`,`b`.`ID` AS `center`,`c`.`ID` AS `top` from ((`anag_user` `a` left join `anag_user` `b` on((`a`.`REFERENCE` = `b`.`ID`))) left join `anag_user` `c` on((`b`.`REFERENCE` = `c`.`ID`)));

ALTER TABLE `anag_user`
  ADD CONSTRAINT `REFERENCE_ID` FOREIGN KEY (`REFERENCE`) REFERENCES `anag_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `app_activation`
  ADD CONSTRAINT `ACT_USER` FOREIGN KEY (`USER`) REFERENCES `anag_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `app_transactions`
  ADD CONSTRAINT `USER_AMOUNT` FOREIGN KEY (`USER`) REFERENCES `anag_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
